//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qatar_2022 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Cargapaises {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cargapaises() {
        }

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.CheckBox Ganomundiales;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox ingresoNombre;
        private System.Windows.Forms.TextBox ingresocontinente;
        private System.Windows.Forms.TextBox ingresoranquing;
        private System.Windows.Forms.TextBox ingresohabitantes;
        private System.Windows.Forms.ComboBox comboGanador;
        private System.Windows.Forms.ComboBox comboparticipaciones;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.DataGridView DGVPais;
        private System.Windows.Forms.DataGridViewTextBoxColumn Pais;
        private System.Windows.Forms.DataGridViewTextBoxColumn Continente;
        private System.Windows.Forms.DataGridViewTextBoxColumn Ranking;
        private System.Windows.Forms.DataGridViewTextBoxColumn Habitantes;
        private System.Windows.Forms.DataGridViewCheckBoxColumn dataGridViewCheckBoxColumn1;
        private System.Windows.Forms.DataGridViewComboBoxColumn Cuantos;
        private System.Windows.Forms.DataGridViewComboBoxColumn Participo;
        private System.Windows.Forms.Button botonguardar;
        private System.Windows.Forms.Button botonEliminar;
        private System.Windows.Forms.Button bajarranking;
        private System.Windows.Forms.Button AgregarMundial;
        private System.Windows.Forms.Button SubirRanking;
        private System.Windows.Forms.Button botonModificar;
        private System.Windows.Forms.TextBox textBoxbuscador;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Button buttonbuscar;

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qatar_2022.Cargapaises", typeof(Cargapaises).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool Continente_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Continente.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool Cuantos_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Cuantos.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool habitantes_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("habitantes.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool Mundial_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Mundial.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool Pais_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Pais.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool Participaciones_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Participaciones.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Boolean similar a True.
        /// </summary>
        public static bool Ranking_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Ranking.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
